## Python Study : Numpy 

In [4]:
import numpy as np

想必大家都還記得 : 

In [1]:
[a for a in range(5)]

[0, 1, 2, 3, 4]

In [2]:
a=[a for a in range(5)]
a*2

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

In [5]:
a=np.array([a for a in range(5)])
a+=1
a

array([1, 2, 3, 4, 5])

In [6]:
b=np.arange(2,11,2)
print('a={0}\nb={1}'.format(a,b),'\na*b=',a*b)
print('a={0}\nb={1}\na*b={2}'.format(a,b,a*b))

a=[1 2 3 4 5]
b=[ 2  4  6  8 10] 
a*b= [ 2  8 18 32 50]
a=[1 2 3 4 5]
b=[ 2  4  6  8 10]
a*b=[ 2  8 18 32 50]


In [7]:
a[0]

1

In [8]:
b[0:5:2]

array([ 2,  6, 10])

## 重要屬性
ndarray.ndim：NumPy ndarray物件的維度 <br/>
ndarry.shape：ndarry物件的每一個維度的大小(size)，回傳資料類別為Tuple <br/>
ndarry.size：ndarry物件所組成之array的總元素數量，回應之數值會等於ndarray.shape的每個元素相乘 <br/>
ndarry.dtype：ndarray物件內組成元素的型態 <br/>
ndarray.itemsize：陣列中每一個元素的大小(Bytes) (ex: int16=>16/8=2 Bytes) <br/>

In [9]:
print('a:{0}'.format(a))
print('ndarray.ndim: {0}'.format(a.ndim))
print('ndarry.shape:{0}'.format(a.shape))
print('ndarry.size:{0}'.format(a.size))
print('ndarry.dtype:{0}'.format(a.dtype))
print('ndarry.itemsize:{0}'.format(a.itemsize))

a:[1 2 3 4 5]
ndarray.ndim: 1
ndarry.shape:(5,)
ndarry.size:5
ndarry.dtype:int32
ndarry.itemsize:4


建置二維陣列

In [10]:
c=np.array([np.arange(0,2),np.arange(2,5,2)])
c

array([[0, 1],
       [2, 4]])

In [12]:
d=np.array(np.arange(1,5))
d

array([1, 2, 3, 4])

In [34]:
d=np.array(np.arange(1,7)).reshape(2,-1)
d

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
d.T

array([[1, 3],
       [2, 4]])

In [15]:
print('d乘c:\n{0}\n c乘d\n{1}'.format(d.dot(c),c.dot(d)))

d乘c:
[[ 4  9]
 [ 8 19]]
 c乘d
[[ 3  4]
 [14 20]]


In [18]:
e=10*np.random.random((2,3)).round(decimals=2)
f=np.ones((4,2),dtype=np.int)
print('e=',e)
print('f=',f)

e= [[6.3 6.8 3.1]
 [9.9 3.7 1.3]]
f= [[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [20]:
np.dot(f,e)

array([[16.2, 10.5,  4.4],
       [16.2, 10.5,  4.4],
       [16.2, 10.5,  4.4],
       [16.2, 10.5,  4.4]])

In [21]:
a.dot(b)

110

In [24]:
b.shape

(5,)

In [25]:
a=a.reshape(5,1)
b=np.reshape(b,(1,5))

In [26]:
print('a乘b:\n{0}\n b乘a\n{1}'.format(a.dot(b),b.dot(a)))

a乘b:
[[ 2  4  6  8 10]
 [ 4  8 12 16 20]
 [ 6 12 18 24 30]
 [ 8 16 24 32 40]
 [10 20 30 40 50]]
 b乘a
[[110]]


## numpy 函數
np.sin(), np.cos(), np.exp(),np.log(),np.mean(),np.median() <br/>
族繁不及備載

In [27]:
np.pi

3.141592653589793

In [32]:
def f(x):
    return (1/np.sqrt(2*np.pi*5))*np.exp(-(x-7)**2/2*5)

In [33]:
f(7)

0.1784124116152771

####  針對不同axis做運算

![123](https://i.imgur.com/1cX8JOO.png)

In [35]:
g=np.array(range(12)).reshape((2,2,3))
g

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [36]:
g.max()

11

In [37]:
g.max(axis=0)

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
g.max(axis=1)

array([[ 3,  4,  5],
       [ 9, 10, 11]])

In [39]:
g.max(axis=2)

array([[ 2,  5],
       [ 8, 11]])